// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"context"

	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// FindByVKID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByVKID(ctx context.Context, id int64) (*User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByVKID")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByVKID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByVKID'
type MockRepository_FindByVKID_Call struct {
	*mock.Call
}

// FindByVKID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepository_Expecter) FindByVKID(ctx interface{}, id interface{}) *MockRepository_FindByVKID_Call {
	return &MockRepository_FindByVKID_Call{Call: _e.mock.On("FindByVKID", ctx, id)}
}

func (_c *MockRepository_FindByVKID_Call) Run(run func(ctx context.Context, id int64)) *MockRepository_FindByVKID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByVKID_Call) Return(user *User, err error) *MockRepository_FindByVKID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_FindByVKID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*User, error)) *MockRepository_FindByVKID_Call {
	_c.Call.Return(run)
	return _c
}

// IncreaseCreditsTx provides a mock function for the type MockRepository
func (_mock *MockRepository) IncreaseCreditsTx(ctx context.Context, tx pgx.Tx, id int64, credits int64) error {
	ret := _mock.Called(ctx, tx, id, credits)

	if len(ret) == 0 {
		panic("no return value specified for IncreaseCreditsTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64, int64) error); ok {
		r0 = returnFunc(ctx, tx, id, credits)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_IncreaseCreditsTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncreaseCreditsTx'
type MockRepository_IncreaseCreditsTx_Call struct {
	*mock.Call
}

// IncreaseCreditsTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - id int64
//   - credits int64
func (_e *MockRepository_Expecter) IncreaseCreditsTx(ctx interface{}, tx interface{}, id interface{}, credits interface{}) *MockRepository_IncreaseCreditsTx_Call {
	return &MockRepository_IncreaseCreditsTx_Call{Call: _e.mock.On("IncreaseCreditsTx", ctx, tx, id, credits)}
}

func (_c *MockRepository_IncreaseCreditsTx_Call) Run(run func(ctx context.Context, tx pgx.Tx, id int64, credits int64)) *MockRepository_IncreaseCreditsTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_IncreaseCreditsTx_Call) Return(err error) *MockRepository_IncreaseCreditsTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_IncreaseCreditsTx_Call) RunAndReturn(run func(ctx context.Context, tx pgx.Tx, id int64, credits int64) error) *MockRepository_IncreaseCreditsTx_Call {
	_c.Call.Return(run)
	return _c
}

// ReduceCredits provides a mock function for the type MockRepository
func (_mock *MockRepository) ReduceCredits(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ReduceCredits")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ReduceCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReduceCredits'
type MockRepository_ReduceCredits_Call struct {
	*mock.Call
}

// ReduceCredits is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepository_Expecter) ReduceCredits(ctx interface{}, id interface{}) *MockRepository_ReduceCredits_Call {
	return &MockRepository_ReduceCredits_Call{Call: _e.mock.On("ReduceCredits", ctx, id)}
}

func (_c *MockRepository_ReduceCredits_Call) Run(run func(ctx context.Context, id int64)) *MockRepository_ReduceCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ReduceCredits_Call) Return(err error) *MockRepository_ReduceCredits_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ReduceCredits_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockRepository_ReduceCredits_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockRepository
func (_mock *MockRepository) Upsert(ctx context.Context, user *User) (*User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *User) (*User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *User) *User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - user *User
func (_e *MockRepository_Expecter) Upsert(ctx interface{}, user interface{}) *MockRepository_Upsert_Call {
	return &MockRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, user)}
}

func (_c *MockRepository_Upsert_Call) Run(run func(ctx context.Context, user *User)) *MockRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *User
		if args[1] != nil {
			arg1 = args[1].(*User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Upsert_Call) Return(user1 *User, err error) *MockRepository_Upsert_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, user *User) (*User, error)) *MockRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
