// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package vk

import (
	"context"

	"github.com/boliev/graphai/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// newMockai creates a new instance of mockai. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockai(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockai {
	mock := &mockai{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockai is an autogenerated mock type for the ai type
type mockai struct {
	mock.Mock
}

type mockai_Expecter struct {
	mock *mock.Mock
}

func (_m *mockai) EXPECT() *mockai_Expecter {
	return &mockai_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type mockai
func (_mock *mockai) Send(ctx context.Context, description string, files []string) (*domain.AIResponse, error) {
	ret := _mock.Called(ctx, description, files)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 *domain.AIResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) (*domain.AIResponse, error)); ok {
		return returnFunc(ctx, description, files)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) *domain.AIResponse); ok {
		r0 = returnFunc(ctx, description, files)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AIResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, description, files)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockai_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type mockai_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - description string
//   - files []string
func (_e *mockai_Expecter) Send(ctx interface{}, description interface{}, files interface{}) *mockai_Send_Call {
	return &mockai_Send_Call{Call: _e.mock.On("Send", ctx, description, files)}
}

func (_c *mockai_Send_Call) Run(run func(ctx context.Context, description string, files []string)) *mockai_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockai_Send_Call) Return(aIResponse *domain.AIResponse, err error) *mockai_Send_Call {
	_c.Call.Return(aIResponse, err)
	return _c
}

func (_c *mockai_Send_Call) RunAndReturn(run func(ctx context.Context, description string, files []string) (*domain.AIResponse, error)) *mockai_Send_Call {
	_c.Call.Return(run)
	return _c
}
